<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class UsersSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');

        $users = [
            // ── Administrateur principal ──
            [
                'nom'        => 'Administrateur',
                'prenom'     => 'Système',
                'email'      => 'admin@enspm.cm',
                'password'   => password_hash('Admin@1234', PASSWORD_BCRYPT),
                'role'       => 'admin',
                'actif'      => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // ── Chef de Département (CD) ──
            [
                'nom'        => 'INFOTEL',
                'prenom'     => 'Chef Département',
                'email'      => 'cd@enspm.cm',
                'password'   => password_hash('CD@1234', PASSWORD_BCRYPT),
                'role'       => 'cd',
                'actif'      => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // ── Enseignants réels du département INFOTEL ──
            [
                'nom'        => 'FROUMSIA',
                'prenom'     => 'Dr',
                'email'      => 'froumsia@enspm.cm',
                'password'   => password_hash('Enseignant@1234', PASSWORD_BCRYPT),
                'role'       => 'enseignant',
                'actif'      => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nom'        => 'BOUDJOU',
                'prenom'     => 'Dr',
                'email'      => 'boudjou@enspm.cm',
                'password'   => password_hash('Enseignant@1234', PASSWORD_BCRYPT),
                'role'       => 'enseignant',
                'actif'      => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nom'        => 'TOUZA',
                'prenom'     => 'M.',
                'email'      => 'touza@enspm.cm',
                'password'   => password_hash('Enseignant@1234', PASSWORD_BCRYPT),
                'role'       => 'enseignant',
                'actif'      => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nom'        => 'AWE',
                'prenom'     => 'Dr T.',
                'email'      => 'awe.t@enspm.cm',
                'password'   => password_hash('Enseignant@1234', PASSWORD_BCRYPT),
                'role'       => 'enseignant',
                'actif'      => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nom'        => 'AWE',
                'prenom'     => 'Dr S.',
                'email'      => 'awe.s@enspm.cm',
                'password'   => password_hash('Enseignant@1234', PASSWORD_BCRYPT),
                'role'       => 'enseignant',
                'actif'      => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nom'        => 'ABDOULAZIZ',
                'prenom'     => 'Dr',
                'email'      => 'abdoulaziz@enspm.cm',
                'password'   => password_hash('Enseignant@1234', PASSWORD_BCRYPT),
                'role'       => 'enseignant',
                'actif'      => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nom'        => 'ABDOULAZIZ HAMAYADJI',
                'prenom'     => 'Dr',
                'email'      => 'abdoulaziz.hamayadji@enspm.cm',
                'password'   => password_hash('Enseignant@1234', PASSWORD_BCRYPT),
                'role'       => 'enseignant',
                'actif'      => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nom'        => 'NGAZIA',
                'prenom'     => 'M.',
                'email'      => 'ngazia@enspm.cm',
                'password'   => password_hash('Enseignant@1234', PASSWORD_BCRYPT),
                'role'       => 'enseignant',
                'actif'      => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nom'        => 'GAZISSOU',
                'prenom'     => 'Dr',
                'email'      => 'gazissou@enspm.cm',
                'password'   => password_hash('Enseignant@1234', PASSWORD_BCRYPT),
                'role'       => 'enseignant',
                'actif'      => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nom'        => 'NOUNAMO',
                'prenom'     => 'Dr',
                'email'      => 'nounamo@enspm.cm',
                'password'   => password_hash('Enseignant@1234', PASSWORD_BCRYPT),
                'role'       => 'enseignant',
                'actif'      => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nom'        => 'NENEO',
                'prenom'     => 'Pr',
                'email'      => 'neneo@enspm.cm',
                'password'   => password_hash('Enseignant@1234', PASSWORD_BCRYPT),
                'role'       => 'enseignant',
                'actif'      => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nom'        => 'GUIEM',
                'prenom'     => 'Dr',
                'email'      => 'guiem@enspm.cm',
                'password'   => password_hash('Enseignant@1234', PASSWORD_BCRYPT),
                'role'       => 'enseignant',
                'actif'      => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nom'        => 'ANAMAK',
                'prenom'     => 'M.',
                'email'      => 'anamak@enspm.cm',
                'password'   => password_hash('Enseignant@1234', PASSWORD_BCRYPT),
                'role'       => 'enseignant',
                'actif'      => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nom'        => 'WARDA LAZARE',
                'prenom'     => 'Dr',
                'email'      => 'warda@enspm.cm',
                'password'   => password_hash('Enseignant@1234', PASSWORD_BCRYPT),
                'role'       => 'enseignant',
                'actif'      => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nom'        => 'MAMAI',
                'prenom'     => 'M.',
                'email'      => 'mamai@enspm.cm',
                'password'   => password_hash('Enseignant@1234', PASSWORD_BCRYPT),
                'role'       => 'enseignant',
                'actif'      => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nom'        => 'TEMGA',
                'prenom'     => 'M.',
                'email'      => 'temga@enspm.cm',
                'password'   => password_hash('Enseignant@1234', PASSWORD_BCRYPT),
                'role'       => 'enseignant',
                'actif'      => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nom'        => 'ABOUBAKAR',
                'prenom'     => 'M.',
                'email'      => 'aboubakar@enspm.cm',
                'password'   => password_hash('Enseignant@1234', PASSWORD_BCRYPT),
                'role'       => 'enseignant',
                'actif'      => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        $this->db->table('users')->insertBatch($users);
    }
}
